// Code generated by "stringer -type=TypeKind"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeNull-0]
	_ = x[TypeFrame-1]
	_ = x[TypeDefault-2]
	_ = x[TypeAny-3]
	_ = x[TypeInt32-4]
	_ = x[TypeInt64-5]
	_ = x[TypeString-6]
	_ = x[TypeBool-7]
	_ = x[TypeFloat64-8]
	_ = x[TypeFunction-9]
	_ = x[TypeBuiltinFunction-10]
	_ = x[TypeArray-11]
	_ = x[TypeSlice-12]
	_ = x[TypeStruct-13]
	_ = x[TypeInterface-14]
	_ = x[TypeTuple-15]
	_ = x[TypeType-16]
	_ = x[TypeFactory-17]
}

const _TypeKind_name = "TypeNullTypeFrameTypeDefaultTypeAnyTypeInt32TypeInt64TypeStringTypeBoolTypeFloat64TypeFunctionTypeBuiltinFunctionTypeArrayTypeSliceTypeStructTypeInterfaceTypeTupleTypeTypeTypeFactory"

var _TypeKind_index = [...]uint8{0, 8, 17, 28, 35, 44, 53, 63, 71, 82, 94, 113, 122, 131, 141, 154, 163, 171, 182}

func (i TypeKind) String() string {
	if i < 0 || i >= TypeKind(len(_TypeKind_index)-1) {
		return "TypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeKind_name[_TypeKind_index[i]:_TypeKind_index[i+1]]
}
