// Code generated by "stringer -type=InstructionKind"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Add-1]
	_ = x[Sub-2]
	_ = x[Mul-3]
	_ = x[Quo-4]
	_ = x[Mod-5]
	_ = x[Less-6]
	_ = x[Greater-7]
	_ = x[Equals-8]
	_ = x[NotEquals-9]
	_ = x[Move-10]
	_ = x[And-11]
	_ = x[Or-12]
	_ = x[Not-13]
	_ = x[Default-14]
	_ = x[Bool-15]
	_ = x[I8-16]
	_ = x[I16-17]
	_ = x[I32-18]
	_ = x[I64-19]
	_ = x[F32-20]
	_ = x[F64-21]
	_ = x[ProcedureType-22]
	_ = x[ProcedureDefinition-23]
	_ = x[ConstructTuple-24]
	_ = x[LoadEnv-25]
	_ = x[Env-26]
	_ = x[Phi-27]
	_ = x[Ret-28]
	_ = x[End-29]
	_ = x[GotoIf-30]
	_ = x[Goto-31]
	_ = x[Call-32]
	_ = x[Push-33]
	_ = x[Pop-34]
}

const _InstructionKind_name = "UndefinedAddSubMulQuoModLessGreaterEqualsNotEqualsMoveAndOrNotDefaultBoolI8I16I32I64F32F64ProcedureTypeProcedureDefinitionConstructTupleLoadEnvEnvPhiRetEndGotoIfGotoCallPushPop"

var _InstructionKind_index = [...]uint8{0, 9, 12, 15, 18, 21, 24, 28, 35, 41, 50, 54, 57, 59, 62, 69, 73, 75, 78, 81, 84, 87, 90, 103, 122, 136, 143, 146, 149, 152, 155, 161, 165, 169, 173, 176}

func (i InstKind) String() string {
	if i < 0 || i >= InstKind(len(_InstructionKind_index)-1) {
		return "InstructionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstructionKind_name[_InstructionKind_index[i]:_InstructionKind_index[i+1]]
}
