// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[RUNE-6]
	_ = x[STRING-7]
	_ = x[ADD-8]
	_ = x[SUB-9]
	_ = x[MUL-10]
	_ = x[QUO-11]
	_ = x[MOD-12]
	_ = x[AND-13]
	_ = x[OR-14]
	_ = x[XOR-15]
	_ = x[EXPONENT-16]
	_ = x[SHIFT_LEFT-17]
	_ = x[SHIFT_RIGHT-18]
	_ = x[ASSIGN-19]
	_ = x[LOGICAL_AND-20]
	_ = x[LOGICAL_OR-21]
	_ = x[LOGICAL_XOR-22]
	_ = x[EQUAL-23]
	_ = x[LESS-24]
	_ = x[GREATER-25]
	_ = x[NOT-26]
	_ = x[NOT_EQUAL-27]
	_ = x[LESS_EQUAL-28]
	_ = x[GREATER_EQUAL-29]
	_ = x[ELIPSIS-30]
	_ = x[LEFT_PAREN-31]
	_ = x[RIGHT_PAREN-32]
	_ = x[LEFT_BRACK-33]
	_ = x[RIGHT_BRACK-34]
	_ = x[LEFT_BRACE-35]
	_ = x[RIGHT_BRACE-36]
	_ = x[COMMA-37]
	_ = x[PERIOD-38]
	_ = x[SEMICOLON-39]
	_ = x[LEFT_ARROW-40]
	_ = x[RIGHT_ARROW-41]
	_ = x[OPTIONAL-42]
	_ = x[FUNC-43]
	_ = x[FOR-44]
	_ = x[EACH-45]
	_ = x[THEN-46]
	_ = x[ELSE-47]
	_ = x[BREAK-48]
	_ = x[CONTINUE-49]
	_ = x[RETURN-50]
	_ = x[DEFAULT-51]
	_ = x[GO-52]
	_ = x[SELECT-53]
	_ = x[MUTABLE-54]
	_ = x[COMPILE_TIME-55]
	_ = x[RANGE-56]
	_ = x[CHAN-57]
	_ = x[INTERFACE-58]
	_ = x[STRUCT-59]
}

const _Token_name = "ILLEGALEOFCOMMENTIDENTINTFLOATRUNESTRINGADDSUBMULQUOMODANDORXOREXPONENTSHIFT_LEFTSHIFT_RIGHTASSIGNLOGICAL_ANDLOGICAL_ORLOGICAL_XOREQUALLESSGREATERNOTNOT_EQUALLESS_EQUALGREATER_EQUALELIPSISLEFT_PARENRIGHT_PARENLEFT_BRACKRIGHT_BRACKLEFT_BRACERIGHT_BRACECOMMAPERIODSEMICOLONLEFT_ARROWRIGHT_ARROWOPTIONALFUNCFOREACHTHENELSEBREAKCONTINUERETURNDEFAULTGOSELECTMUTABLECOMPILE_TIMERANGECHANINTERFACESTRUCT"

var _Token_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 34, 40, 43, 46, 49, 52, 55, 58, 60, 63, 71, 81, 92, 98, 109, 119, 130, 135, 139, 146, 149, 158, 168, 181, 188, 198, 209, 219, 230, 240, 251, 256, 262, 271, 281, 292, 300, 304, 307, 311, 315, 319, 324, 332, 338, 345, 347, 353, 360, 372, 377, 381, 390, 396}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
