// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[RUNE-6]
	_ = x[STRING-7]
	_ = x[TRUE-8]
	_ = x[FALSE-9]
	_ = x[ADD-10]
	_ = x[SUB-11]
	_ = x[MUL-12]
	_ = x[QUO-13]
	_ = x[MOD-14]
	_ = x[AND-15]
	_ = x[OR-16]
	_ = x[XOR-17]
	_ = x[EXPONENT-18]
	_ = x[SHIFT_LEFT-19]
	_ = x[SHIFT_RIGHT-20]
	_ = x[ASSIGN-21]
	_ = x[LOGICAL_AND-22]
	_ = x[LOGICAL_OR-23]
	_ = x[LOGICAL_XOR-24]
	_ = x[EQUAL-25]
	_ = x[LESS-26]
	_ = x[GREATER-27]
	_ = x[NOT-28]
	_ = x[NOT_EQUAL-29]
	_ = x[LESS_EQUAL-30]
	_ = x[GREATER_EQUAL-31]
	_ = x[ELIPSIS-32]
	_ = x[LEFT_PAREN-33]
	_ = x[RIGHT_PAREN-34]
	_ = x[LEFT_BRACK-35]
	_ = x[RIGHT_BRACK-36]
	_ = x[LEFT_BRACE-37]
	_ = x[RIGHT_BRACE-38]
	_ = x[COMMA-39]
	_ = x[PERIOD-40]
	_ = x[SEMICOLON-41]
	_ = x[LEFT_ARROW-42]
	_ = x[RIGHT_ARROW-43]
	_ = x[OPTIONAL-44]
	_ = x[FUNC-45]
	_ = x[FOR-46]
	_ = x[EACH-47]
	_ = x[THEN-48]
	_ = x[ELSE-49]
	_ = x[BREAK-50]
	_ = x[CONTINUE-51]
	_ = x[RETURN-52]
	_ = x[DEFAULT-53]
	_ = x[GO-54]
	_ = x[SELECT-55]
	_ = x[MATCH-56]
	_ = x[MUTABLE-57]
	_ = x[COMPILE_TIME-58]
	_ = x[RANGE-59]
	_ = x[CHAN-60]
	_ = x[INTERFACE-61]
	_ = x[STRUCT-62]
}

const _Token_name = "ILLEGALEOFCOMMENTIDENTINTFLOATRUNESTRINGTRUEFALSEADDSUBMULQUOMODANDORXOREXPONENTSHIFT_LEFTSHIFT_RIGHTASSIGNLOGICAL_ANDLOGICAL_ORLOGICAL_XOREQUALLESSGREATERNOTNOT_EQUALLESS_EQUALGREATER_EQUALELIPSISLEFT_PARENRIGHT_PARENLEFT_BRACKRIGHT_BRACKLEFT_BRACERIGHT_BRACECOMMAPERIODSEMICOLONLEFT_ARROWRIGHT_ARROWOPTIONALFUNCFOREACHTHENELSEBREAKCONTINUERETURNDEFAULTGOSELECTMATCHMUTABLECOMPILE_TIMERANGECHANINTERFACESTRUCT"

var _Token_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 34, 40, 44, 49, 52, 55, 58, 61, 64, 67, 69, 72, 80, 90, 101, 107, 118, 128, 139, 144, 148, 155, 158, 167, 177, 190, 197, 207, 218, 228, 239, 249, 260, 265, 271, 280, 290, 301, 309, 313, 316, 320, 324, 328, 333, 341, 347, 354, 356, 362, 367, 374, 386, 391, 395, 404, 410}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
