// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[RUNE-6]
	_ = x[STRING-7]
	_ = x[TRUE-8]
	_ = x[FALSE-9]
	_ = x[ADD-10]
	_ = x[SUB-11]
	_ = x[MUL-12]
	_ = x[QUO-13]
	_ = x[MOD-14]
	_ = x[INDEX-15]
	_ = x[AND-16]
	_ = x[OR-17]
	_ = x[XOR-18]
	_ = x[EXPONENT-19]
	_ = x[SHIFT_LEFT-20]
	_ = x[SHIFT_RIGHT-21]
	_ = x[ASSIGN-22]
	_ = x[LOGICAL_AND-23]
	_ = x[LOGICAL_OR-24]
	_ = x[LOGICAL_XOR-25]
	_ = x[EQUAL-26]
	_ = x[LESS-27]
	_ = x[GREATER-28]
	_ = x[NOT-29]
	_ = x[NOT_EQUAL-30]
	_ = x[LESS_EQUAL-31]
	_ = x[GREATER_EQUAL-32]
	_ = x[ELIPSIS-33]
	_ = x[LEFT_PAREN-34]
	_ = x[RIGHT_PAREN-35]
	_ = x[LEFT_BRACK-36]
	_ = x[RIGHT_BRACK-37]
	_ = x[LEFT_BRACE-38]
	_ = x[RIGHT_BRACE-39]
	_ = x[COMMA-40]
	_ = x[PERIOD-41]
	_ = x[SEMICOLON-42]
	_ = x[LEFT_ARROW-43]
	_ = x[RIGHT_ARROW-44]
	_ = x[OPTIONAL-45]
	_ = x[FUNC-46]
	_ = x[FOR-47]
	_ = x[EACH-48]
	_ = x[THEN-49]
	_ = x[ELSE-50]
	_ = x[CONSTRUCT-51]
	_ = x[BREAK-52]
	_ = x[CONTINUE-53]
	_ = x[RETURN-54]
	_ = x[DEFAULT-55]
	_ = x[GO-56]
	_ = x[SELECT-57]
	_ = x[MATCH-58]
	_ = x[MUTABLE-59]
	_ = x[COMPILE_TIME-60]
	_ = x[RANGE-61]
	_ = x[CHAN-62]
	_ = x[INTERFACE-63]
	_ = x[STRUCT-64]
}

const _Token_name = "ILLEGALEOFCOMMENTIDENTINTFLOATRUNESTRINGTRUEFALSEADDSUBMULQUOMODINDEXANDORXOREXPONENTSHIFT_LEFTSHIFT_RIGHTASSIGNLOGICAL_ANDLOGICAL_ORLOGICAL_XOREQUALLESSGREATERNOTNOT_EQUALLESS_EQUALGREATER_EQUALELIPSISLEFT_PARENRIGHT_PARENLEFT_BRACKRIGHT_BRACKLEFT_BRACERIGHT_BRACECOMMAPERIODSEMICOLONLEFT_ARROWRIGHT_ARROWOPTIONALFUNCFOREACHTHENELSECONSTRUCTBREAKCONTINUERETURNDEFAULTGOSELECTMATCHMUTABLECOMPILE_TIMERANGECHANINTERFACESTRUCT"

var _Token_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 34, 40, 44, 49, 52, 55, 58, 61, 64, 69, 72, 74, 77, 85, 95, 106, 112, 123, 133, 144, 149, 153, 160, 163, 172, 182, 195, 202, 212, 223, 233, 244, 254, 265, 270, 276, 285, 295, 306, 314, 318, 321, 325, 329, 333, 342, 347, 355, 361, 368, 370, 376, 381, 388, 400, 405, 409, 418, 424}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
